services:
  - type: web
    name: chatbot-nlp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12

